# Generated by Django 4.1 on 2022-08-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='dop',
            field=models.DateField(default='2000-02-02'),
            preserve_default=False,
        ),
    ]
